name: tc_bootcamp_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:

  animated_text_kit: ^4.2.3
# ek özellik animasyonlu metinler için  
  dio: ^5.8.0+1
  # json işlemleri için
  equatable: ^2.0.7
  # eşitlik kontrolü için
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  # BLoC yapısı için
  provider: ^6.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
